#!/usr/bin/env bash
# Installs and configures HAproxy

# Update packages and install
apt-get update
apt-get -y install --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.6
apt-get -y install haproxy=2.6.\*

# Create backup config file
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bk

# Enable init script
if [ "$(grep -Eco '^ENABLED=[01]$' < /etc/default/haproxy)" -gt 0 ]; then
	sed -i 's/^ENABLED=0$/ENABLED=1/' /etc/default/haproxy
else
	echo "ENABLED=1" >> /etc/default/haproxy
fi

# Add config details to file
CONFIG_DEETS=\
"frontend alx-nnamdi
	bind *:80
	default_backend web-servers

backend web-servers
	balance roundrobin
	server 46107-web-01 44.210.21.227:80 check
	server 46107-web-02 100.25.205.170:80 check"

echo -e "$CONFIG_DEETS" >> /etc/haproxy/haproxy.cfg

# restart haproxy
service haproxy restart
