#!/usr/bin/env bash
# This script is displaying a clock

HOUR=0
MINUTE=1
while ((HOUR<=12)); do
	echo "Hour: $HOUR"
	while ((MINUTE<=59)); do
		echo "$MINUTE"
		((MINUTE++))
	done
	((MINUTE=1))
	((HOUR++))
done
