#!/usr/bin/env bash
# This is a program that changes the addresses for localhost and facebook.com

cp /etc/hosts ~/hosts.new
echo "8.8.8.8	facebook.com" >> ~/hosts.new
echo "127.0.0.2	localhost" >> ~/hosts.new
cat ~/hosts.new > /etc/hosts
