#!/usr/bin/env bash
# Change nginx user to nginx

su - nginx

# Modify config
NEW_CONFIG="server {
	listen 8080;
	listen [::]:8080;
}"
echo -e "$NEW_CONFIG" >> /etc/nginx/sites-enabled/default

# restart nginx and apply updates
service nginx restart
